services:
  node0:
    image: dht-node
    container_name: node0
    tty: true
    stdin_open: true
    hostname: node0
    command: ["./dht", "-entry"]
    ports:
      - "50052:50051"
    volumes:
      - ./data/node0/resources:/app/data/resources
      - ./data/node0/routing:/app/data/routing
    environment:
      - NODE_NAME=node0
      - NODE_PORT=50051
      - ENTRY_HOST=node0
      - ENTRY_PORT=50051
    restart: "no"

  node1:
    image: dht-node
    container_name: node1
    tty: true
    stdin_open: true
    hostname: node1
    command: ["./dht"]
    ports:
      - "50053:50051"
    volumes:
      - ./data/node1/resources:/app/data/resources
      - ./data/node1/routing:/app/data/routing
    environment:
      - ENTRY_HOST=node0
      - ENTRY_PORT=50051
    depends_on:
      - node0
    restart: "no"

  node2:
    image: dht-node
    container_name: node2
    tty: true
    stdin_open: true
    hostname: node2
    command: ["./dht"]
    ports:
      - "50054:50051"
    volumes:
      - ./data/node2/resources:/app/data/resources
      - ./data/node2/routing:/app/data/routing
    environment:
      - ENTRY_HOST=node0
      - ENTRY_PORT=50051
    depends_on:
      - node0
    restart: "no"

  node3:
    image: dht-node
    container_name: node3
    tty: true
    stdin_open: true
    hostname: node3
    command: ["./dht"]
    ports:
      - "50055:50051"
    volumes:
      - ./data/node3/resources:/app/data/resources
      - ./data/node3/routing:/app/data/routing
    environment:
      - ENTRY_HOST=node0
      - ENTRY_PORT=50051
    depends_on:
      - node0
    restart: "no"

  node4:
    image: dht-node
    container_name: node4
    tty: true
    stdin_open: true
    hostname: node4
    command: ["./dht"]
    ports:
      - "50056:50051"
    volumes:
      - ./data/node4/resources:/app/data/resources
      - ./data/node4/routing:/app/data/routing
    environment:
      - ENTRY_HOST=node0
      - ENTRY_PORT=50051
    depends_on:
      - node0
    restart: "no"

  node5:
    image: dht-node
    container_name: node5
    tty: true
    stdin_open: true
    hostname: node5
    command: ["./dht"]
    ports:
      - "50057:50051"
    volumes:
      - ./data/node5/resources:/app/data/resources
      - ./data/node5/routing:/app/data/routing
    environment:
      - ENTRY_HOST=node0
      - ENTRY_PORT=50051
    depends_on:
      - node0
    restart: "no"

  node6:
    image: dht-node
    container_name: node6
    tty: true
    stdin_open: true
    hostname: node6
    command: ["./dht"]
    ports:
      - "50058:50051"
    volumes:
      - ./data/node6/resources:/app/data/resources
      - ./data/node6/routing:/app/data/routing
    environment:
      - ENTRY_HOST=node0
      - ENTRY_PORT=50051
    depends_on:
      - node0
    restart: "no"

  node7:
    image: dht-node
    container_name: node7
    tty: true
    stdin_open: true
    hostname: node7
    command: ["./dht"]
    ports:
      - "50059:50051"
    volumes:
      - ./data/node7/resources:/app/data/resources
      - ./data/node7/routing:/app/data/routing
    environment:
      - ENTRY_HOST=node0
      - ENTRY_PORT=50051
    depends_on:
      - node0
    restart: "no"

  node8:
    image: dht-node
    container_name: node8
    tty: true
    stdin_open: true
    hostname: node8
    command: ["./dht"]
    ports:
      - "50060:50051"
    volumes:
      - ./data/node8/resources:/app/data/resources
      - ./data/node8/routing:/app/data/routing
    environment:
      - ENTRY_HOST=node0
      - ENTRY_PORT=50051
    depends_on:
      - node0
    restart: "no"

  node9:
    image: dht-node
    container_name: node9
    tty: true
    stdin_open: true
    hostname: node9
    command: ["./dht"]
    ports:
      - "50061:50051"
    volumes:
      - ./data/node9/resources:/app/data/resources
      - ./data/node9/routing:/app/data/routing
    environment:
      - ENTRY_HOST=node0
      - ENTRY_PORT=50051
    depends_on:
      - node0
    restart: "no"

networks:
  dht_net:
    driver: bridge
