services:
  node0:
    image: dht-node
    container_name: node0
    hostname: node0
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    ports:
      - "50052:50051"
    volumes:
      - /app/data
    environment:
      - NODE_NAME=node0
      - NODE_PORT=50051
    restart: "no"

  node1:
    image: dht-node
    container_name: node1
    hostname: node1
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    ports:
      - "50053:50051"
    volumes:
      - /app/data
    environment:
      - NODE_NAME=node1
      - NODE_PORT=50052
      - ENTRY_HOST=node0
      - ENTRY_PORT=50051
    depends_on:
      - node0
    restart: "no"

  node2:
    image: dht-node
    container_name: node2
    hostname: node2
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    ports:
      - "50054:50051"
    volumes:
      - /app/data
    environment:
      - NODE_NAME=node2
      - NODE_PORT=50053
      - ENTRY_HOST=node0
      - ENTRY_PORT=50051
    depends_on:
      - node0
    restart: "no"

networks:
  dht_net:
    driver: bridge
